### ISSUE TITLE
make error Please add -D_FILE_OFFSET_BITS=64

### ISSUE THREAD

**Issue by GoogleCodeExporter** [rbrito/rdiff-backup-fs#6]
```
I am trying to compile with 64 bit Ubuntu 10.10 (32 bit was ok). The error I 
get is:

make
make  all-recursive
make[1]: Entering directory 
`/home/go/projects/rdiff-backup-fs/rdiff-backup-fs-1.0.0'
Making all in layout
make[2]: Entering directory 
`/home/go/projects/rdiff-backup-fs/rdiff-backup-fs-1.0.0/layout'
gcc -DHAVE_CONFIG_H -I. -I..     -Wall -O3  -MT all.o -MD -MP -MF .deps/all.Tpo 
-c -o all.o all.c
In file included from /usr/include/fuse/fuse.h:26,
                 from /usr/include/fuse.h:9,
                 from ../externs.h:6,
                 from all.h:5,
                 from all.c:1:
/usr/include/fuse/fuse_common.h:32: error: #error Please add 
-D_FILE_OFFSET_BITS=64 to your compile flags!
make[2]: *** [all.o] Error 1
make[2]: Leaving directory 
`/home/go/projects/rdiff-backup-fs/rdiff-backup-fs-1.0.0/layout'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory 
`/home/go/projects/rdiff-backup-fs/rdiff-backup-fs-1.0.0'
make: *** [all] Error 2

```

Original issue reported on code.google.com by `mek...@gmail.com` on 7 May 2011 at 6:14

**Comment by k3dar** [comment]
This issue was moved to k3dar/rdiff-backup-fs#6
